/* Ritmi v2: iPhone-first, local-first cycle tracker. */
(function () {
  'use strict';
  var DB='nijritu-local', VER=4, STORE='state', KEY='state';
  var today=new Date(), state={version:'0.20.0',profile:null,logs:{},settings:{},customSymptoms:[]};
  var view='home', month=new Date(today.getFullYear(),today.getMonth(),1), memoryOnly=false;
  function $(id){return document.getElementById(id)}
  function pad(n){return n<10?'0'+n:String(n)}
  function key(d){d=new Date(d);return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}
  function date(k){var p=k.split('-');return new Date(+p[0],+p[1]-1,+p[2])}
  function add(k,n){var d=date(k);d.setDate(d.getDate()+n);return key(d)}
  function days(a,b){return Math.round((date(b)-date(a))/86400000)}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function fmt(k,opt){return date(k).toLocaleDateString(undefined,opt)}
  function starts(){return Object.keys(state.logs).filter(function(k){return state.logs[k]&&state.logs[k].period}).sort()}
  function lengths(){var s=starts(),o=[];for(var i=1;i<s.length;i++){var n=days(s[i-1],s[i]);if(n>=15&&n<=90)o.push(n)}return o.slice(-8)}
  function avg(a,f){if(!a.length)return f;return Math.round(a.reduce(function(x,y){return x+y},0)/a.length)}
  function metrics(){var s=starts(),ls=lengths(),cycle=+(state.profile&&state.profile.cycleLength)||avg(ls,28),period=+(state.profile&&state.profile.periodLength)||5,last=s.length?s[s.length-1]:null,next=last?add(last,cycle):null,day=last?days(last,key(today))+1:null;return{starts:s,lengths:ls,cycle:cycle,period:period,last:last,next:next,day:day}}
  function phase(day,cycle){if(!day)return'No cycle baseline';if(day<=5)return'Period';if(day<=Math.round(cycle*.5))return'Follicular';if(day<=Math.round(cycle*.6))return'Ovulation estimate';return'Luteal'}
  function db(){return new Promise(function(resolve,reject){if(!window.indexedDB){memoryOnly=true;reject(new Error('no indexedDB'));return}var r;try{r=indexedDB.open(DB,VER)}catch(e){memoryOnly=true;reject(e);return}r.onupgradeneeded=function(){if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=function(){resolve(r.result)};r.onerror=function(){reject(r.error||new Error('storage'))}})}
  function read(){if(memoryOnly)return Promise.resolve(null);return db().then(function(d){return new Promise(function(res,rej){var r=d.transaction(STORE,'readonly').objectStore(STORE).get(KEY);r.onsuccess=function(){res(r.result||null)};r.onerror=function(){rej(r.error)}})})}
  function save(){if(memoryOnly)return Promise.resolve();return db().then(function(d){return new Promise(function(res,rej){var t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(state,KEY);t.oncomplete=res;t.onerror=function(){rej(t.error)}})})}
  function normalize(s){if(!s)return;state=Object.assign(state,s);state.logs=s.logs&&typeof s.logs==='object'?s.logs:{};state.settings=Object.assign({},s.settings||{});state.customSymptoms=Array.isArray(s.customSymptoms)?s.customSymptoms:[]}
  function navIcon(n){var p={home:'<circle cx="12" cy="12" r="8"/><path d="M12 8v4l3 2"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18"/>',insights:'<path d="M4 19V11M10 19V6M16 19v13M22 19H2"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19 15l2 1-2 3-2-1a7 7 0 0 1-2 1l-.3 2h-3.4L11 19a7 7 0 0 1-2-1l-2 1-2-3 2-1a7 7 0 0 1 0-2l-2-1 2-3 2 1a7 7 0 0 1 2-1l.3-2h3.4L15 5a7 7 0 0 1 2 1l2-1 2 3-2 1a7 7 0 0 1 0 2z"/>'};return'<svg viewBox="0 0 24 24" aria-hidden="true">'+p[n]+'</svg>'}
  function shell(content){return '<div class="screen">'+content+'</div><nav class="dock"><button data-view="home" class="'+(view==='home'?'on':'')+'">'+navIcon('home')+'<span>Rhythm</span></button><button data-view="calendar" class="'+(view==='calendar'?'on':'')+'">'+navIcon('calendar')+'<span>Calendar</span></button><button data-view="insights" class="'+(view==='insights'?'on':'')+'">'+navIcon('insights')+'<span>Patterns</span></button><button data-view="settings" class="'+(view==='settings'?'on':'')+'">'+navIcon('settings')+'<span>More</span></button></nav>'}
  function render(){var app=$('app');if(!app)return;var c=view==='calendar'?calendar():view==='insights'?insights():view==='settings'?settings():home();app.innerHTML=shell(c);bind();if(!state.profile)showOnboarding()}
  function home(){var m=metrics(),k=key(today),l=state.logs[k]||{},progress=m.day?Math.max(0,Math.min(1,(m.day-1)/Math.max(1,m.cycle-1))):0,next=m.next?fmt(m.next,{month:'short',day:'numeric'}):'Set baseline';return '<header class="top"><div><span class="micro">RITMI / '+fmt(k,{weekday:'short',month:'short',day:'numeric'}).toUpperCase()+'</span><h1>Good morning.</h1></div><button class="round-control" data-view="settings" aria-label="Settings">'+navIcon('settings')+'</button></header><main class="rhythm-main"><section class="dial" style="--p:'+progress+'"><div class="dial-grid"></div><div class="dial-ring ring-one"></div><div class="dial-ring ring-two"></div><div class="dial-marker" style="transform:rotate('+(progress*360)+'deg)"></div><div class="dial-core"><span class="micro">CYCLE DAY</span><strong>'+(m.day||'—')+'</strong><em>'+(m.day?phase(m.day,m.cycle):'Start with your last period')+'</em></div><span class="dial-tick t1"></span><span class="dial-tick t2"></span><span class="dial-tick t3"></span><span class="dial-tick t4"></span></section><section class="readout"><div><span>Next period</span><strong>'+esc(next)+'</strong></div><div><span>Cycle</span><strong>'+m.cycle+' days</strong></div></section><button class="log-trigger" data-action="log"><span class="plus">+</span><span><b>'+(l.period?'Update today':'Log today')+'</b><small>'+(l.period?'Period recorded':'Flow, pain or note')+'</small></span><i>↗</i></button><section class="signal"><span class="signal-dot"></span><div><b>Private by design</b><p>Your entries live on this iPhone. No account. No tracking.</p></div></section></main>'}
  function calendar(){var y=month.getFullYear(),mo=month.getMonth(),first=new Date(y,mo,1),last=new Date(y,mo+1,0),off=first.getDay(),total=Math.ceil((off+last.getDate())/7)*7,m=metrics(),pred={},h='<header class="page-top"><button class="backless" data-action="month-today">Today</button><div><span class="micro">HISTORY</span><h1>Calendar</h1></div><span></span></header><div class="month-nav"><button data-action="prev">‹</button><strong>'+month.toLocaleDateString(undefined,{month:'long',year:'numeric'})+'</strong><button data-action="next">›</button></div><div class="week">'+['S','M','T','W','T','F','S'].map(function(x){return'<span>'+x+'</span>'}).join('')+'</div><div class="days">';if(m.next)for(var q=0;q<m.period;q++)pred[add(m.next,q)]=1;for(var i=0;i<total;i++){if(i<off||i>=off+last.getDate()){h+='<span></span>';continue}var d=new Date(y,mo,i-off+1),k=key(d),l=state.logs[k],cl=k===key(today)?' today':'';if(l&&l.period)cl+=' period';else if(pred[k])cl+=' predicted';if(l&&(l.flow||l.pain||l.notes))cl+=' logged';h+='<button class="day'+cl+'" data-action="date" data-date="'+k+'"><span>'+d.getDate()+'</span></button>'}return h+'</div><div class="calendar-foot"><span><i class="leg-period"></i>Period</span><span><i class="leg-pred"></i>Estimated</span><span><i class="leg-note"></i>Logged</span></div>'}
  function insights(){var m=metrics(),ls=m.lengths,range=ls.length?Math.min.apply(null,ls)+'–'+Math.max.apply(null,ls):'—',bars=ls.map(function(n){return'<div class="bar"><i style="height:'+Math.max(16,Math.round(n/Math.max.apply(null,ls)*100))+'%"></i><span>'+n+'</span></div>'}).join('');return '<header class="page-top"><div><span class="micro">YOUR DATA</span><h1>Patterns.</h1></div></header><section class="big-stat"><span>Typical cycle</span><strong>'+m.cycle+'<small>days</small></strong><p>'+(ls.length?'Based on your recorded cycle starts.':'Add a few period starts and Ritmi will show your own history here.')+'</p></section><section class="chart-block"><div class="chart-head"><span>Recent cycles</span><b>'+range+' days</b></div><div class="bars">'+(bars||'<div class="chart-empty">Your history will appear here.</div>')+'</div></section><section class="note-block"><span>RITMI NOTE</span><p>Estimates are simple calendar calculations from what you record. They are not medical predictions or diagnoses.</p></section>'}
  function settings(){var m=metrics();return '<header class="page-top"><div><span class="micro">RITMI</span><h1>More.</h1></div></header><section class="settings-list"><button data-action="baseline"><span><b>Cycle baseline</b><small>'+m.cycle+' day cycle · '+m.period+' day period</small></span><i>›</i></button><button data-action="export"><span><b>Export my data</b><small>Download a JSON copy of everything stored here</small></span><i>↗</i></button><button data-action="import"><span><b>Import data</b><small>Restore a previous Ritmi export</small></span><i>↗</i></button><button data-action="privacy"><span><b>Privacy</b><small>No account · local storage · no analytics</small></span><i>›</i></button></section><section class="settings-bottom"><span>RITMI 0.20</span><button data-action="reset">Erase all local data</button></section><input id="import-file" type="file" accept="application/json" hidden />'}
  function overlay(title,html){var old=$('overlay');if(old)old.remove();var d=document.createElement('div');d.id='overlay';d.className='overlay';d.innerHTML='<div class="overlay-back" data-action="close"></div><section class="overlay-panel"><button class="close" data-action="close">×</button><span class="micro">'+title.toUpperCase()+'</span>'+html+'</section>';document.body.appendChild(d);bind()}
  function logForm(k){var l=state.logs[k]||{};overlay('Log '+fmt(k,{month:'short',day:'numeric'}),'<form id="log-form"><label class="toggle-line"><input id="period" type="checkbox" '+(l.period?'checked':'')+'><span class="fake-toggle"></span><b>Period day</b><small>Count this date as a period start/day</small></label><div class="field-row"><label>Flow<select id="flow"><option value="">None</option><option '+(l.flow==='Spotting'?'selected':'')+'>Spotting</option><option '+(l.flow==='Light'?'selected':'')+'>Light</option><option '+(l.flow==='Medium'?'selected':'')+'>Medium</option><option '+(l.flow==='Heavy'?'selected':'')+'>Heavy</option></select></label><label>Pain<select id="pain"><option value="">None</option><option '+(l.pain==='None'?'selected':'')+'>None</option><option '+(l.pain==='Mild'?'selected':'')+'>Mild</option><option '+(l.pain==='Moderate'?'selected':'')+'>Moderate</option><option '+(l.pain==='Severe'?'selected':'')+'>Severe</option></select></label></div><label>Note<input id="notes" maxlength="300" value="'+esc(l.notes||'')+'" placeholder="A quiet note for later"></label><button class="primary" type="submit">Save</button></form>');$('log-form').addEventListener('submit',function(e){e.preventDefault();var p=$('period').checked,f=$('flow').value,pa=$('pain').value,n=$('notes').value.trim();if(p||f||pa||n)state.logs[k]={period:p,flow:f,pain:pa,notes:n};else delete state.logs[k];save().then(function(){closeOverlay();render()})})}
  function baseline(){var p=state.profile||{};overlay('Cycle baseline','<form id="base-form"><label>Last period started<input id="start" type="date" value="'+esc(p.start||'')+'" required></label><div class="field-row"><label>Cycle length<input id="cycle" type="number" min="15" max="90" value="'+(p.cycleLength||28)+'" required></label><label>Period length<input id="periodlen" type="number" min="1" max="15" value="'+(p.periodLength||5)+'" required></label></div><button class="primary" type="submit">Save baseline</button></form>');$('base-form').addEventListener('submit',function(e){e.preventDefault();var s=$('start').value;state.profile={start:s,cycleLength:+$('cycle').value,periodLength:+$('periodlen').value};state.logs[s]=Object.assign({},state.logs[s],{period:true});save().then(function(){closeOverlay();render()})})}
  function showOnboarding(){if($('onboarding'))return;var d=document.createElement('div');d.id='onboarding';d.className='welcome';d.innerHTML='<div class="welcome-mark">R</div><div class="welcome-copy"><span class="micro">RITMI</span><h1>A cycle tracker<br>that stays yours.</h1><p>No account. No feed. No cloud history. Just a quiet tool that lives on this iPhone.</p></div><form id="welcome-form"><label>When did your last period start?<input id="wstart" type="date" required></label><div class="field-row"><label>Cycle<input id="wcycle" type="number" min="15" max="90" value="28" required></label><label>Period<input id="wperiod" type="number" min="1" max="15" value="5" required></label></div><button class="primary" type="submit">Enter Ritmi <span>↗</span></button><small>Stored locally in this browser.</small></form>';document.body.appendChild(d);$('welcome-form').addEventListener('submit',function(e){e.preventDefault();var s=$('wstart').value;state.profile={start:s,cycleLength:+$('wcycle').value,periodLength:+$('wperiod').value};state.logs[s]={period:true};save().then(function(){d.remove();render()})})}
  function closeOverlay(){var o=$('overlay');if(o)o.remove()}
  function bind(){Array.prototype.forEach.call(document.querySelectorAll('[data-view]'),function(b){b.onclick=function(){view=b.getAttribute('data-view');render()}});Array.prototype.forEach.call(document.querySelectorAll('[data-action]'),function(b){b.onclick=function(){var a=b.getAttribute('data-action');if(a==='log')logForm(key(today));else if(a==='date')logForm(b.getAttribute('data-date'));else if(a==='prev'){month=new Date(month.getFullYear(),month.getMonth()-1,1);render()}else if(a==='next'){month=new Date(month.getFullYear(),month.getMonth()+1,1);render()}else if(a==='month-today'){month=new Date(today.getFullYear(),today.getMonth(),1);render()}else if(a==='close')closeOverlay();else if(a==='baseline')baseline();else if(a==='export')exportData();else if(a==='import')$('import-file').click();else if(a==='privacy')overlay('Privacy','<div class="privacy-copy"><h2>Your data stays here.</h2><p>Ritmi does not require an account and does not send cycle entries to a server. Data is stored in this browser using IndexedDB.</p><p>Export creates a local JSON file. Import replaces the current local state with that file.</p></div>');else if(a==='reset')reset();}});var f=$('import-file');if(f)f.onchange=function(){if(f.files[0])importData(f.files[0])}}
  function exportData(){var blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ritmi-data-'+key(today)+'.json';a.click();setTimeout(function(){URL.revokeObjectURL(url)},500)}
  function importData(file){var r=new FileReader();r.onload=function(){try{var x=JSON.parse(r.result);if(!x||typeof x!=='object'||!x.logs)throw new Error();normalize(x);save().then(render)}catch(e){alert('That file is not a valid Ritmi export.')}};r.readAsText(file)}
  function reset(){if(!confirm('Erase all Ritmi data from this browser? This cannot be undone.'))return;state={version:'0.20.0',profile:null,logs:{},settings:{},customSymptoms:[]};save().then(render)}
  read().then(function(s){normalize(s);render()}).catch(function(){memoryOnly=true;render()});
})();