/* NijRitu V0.4 public boundary. Private tracker remains usable without this layer. */
(function(){
  const API_KEY='nijritu.apiBase';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const originalSettings=window.settings,originalRender=window.render;
  const apiBase=()=>String(localStorage.getItem(API_KEY)||'').replace(/\/$/,'');
  const b64=u=>btoa(String.fromCharCode(...new Uint8Array(u))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
  const unb64=s=>{s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))};
  const text=new TextEncoder(),dec=new TextDecoder();
  async function keyFrom(pass,salt){return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},await crypto.subtle.importKey('raw',text.encode(pass),'PBKDF2',false,['deriveKey']),{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
  function snapshot(){const settings={...(state.settings||{})};delete settings.remoteBackup;return JSON.stringify({schema:4,exportedAt:new Date().toISOString(),profile:state.profile,logs:state.logs,customSymptoms:state.customSymptoms,settings})}
  async function encryptSnapshot(pass){if(!pass||pass.length<10)throw Error('Use a passphrase of at least 10 characters.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await keyFrom(pass,salt),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,text.encode(snapshot()));return `NJRV04.${b64(salt)}.${b64(iv)}.${b64(cipher)}`}
  async function decryptSnapshot(blob,pass){const p=String(blob).split('.');if(p.length!==4||p[0]!=='NJRV04')throw Error('Unsupported NijRitu encrypted backup.');const key=await keyFrom(pass,unb64(p[1])),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(p[2])},key,unb64(p[3]));const x=JSON.parse(dec.decode(plain));if(!x||!x.logs||!x.profile)throw Error('Invalid backup data.');return x}
  function remoteCard(){return `<article class="card"><p class="eyebrow">Encrypted backup</p><h2 class="section-title">Put the backup where you choose.</h2><p class="muted">NijRitu encrypts the tracker snapshot in this browser before upload. The remote service receives only ciphertext and never receives your passphrase.</p><label class="field"><span>Passphrase</span><input id="v04Pass" type="password" minlength="10" autocomplete="new-password" placeholder="10+ characters"></label><label class="field"><span>WebDAV / Nextcloud file URL</span><input id="v04Dav" inputmode="url" placeholder="https://cloud.example/remote.php/dav/files/me/nijritu.njr"></label><div class="field-grid"><label><span>Username <em>optional</em></span><input id="v04User" autocomplete="username"></label><label><span>Password <em>not stored</em></span><input id="v04Pwd" type="password" autocomplete="current-password"></label></div><div class="button-row"><button class="button primary small" data-action="webdavPut">Upload encrypted backup</button><button class="button ghost small" data-action="webdavGet">Restore from WebDAV</button></div><div class="divider"></div><p class="eyebrow">Optional NijRitu relay</p><label class="field"><span>API base</span><input id="v04Api" value="${esc(apiBase())}" placeholder="https://your-server.example"></label><div class="button-row"><button class="button ghost small" data-action="apiSave">Save endpoint locally</button><button class="button ghost small" data-action="relayPut">Upload ciphertext</button><button class="button ghost small" data-action="relayGet">Restore ciphertext</button></div><p class="muted tiny">The relay is an optional convenience. It stores opaque encrypted bytes only. For the strongest ownership model, use your own WebDAV or Nextcloud destination.</p></article>`}
  window.settings=()=>remoteCard()+originalSettings();
  async function webdav(url,user,pwd,method,body){const h={'cache-control':'no-store'};if(user||pwd)h.authorization='Basic '+btoa(`${user}:${pwd}`);const r=await fetch(url,{method,headers:h,body});if(!r.ok)throw Error(`WebDAV request failed (${r.status}). Check the URL, credentials and CORS.`);return r}
  async function putWebdav(){const url=document.getElementById('v04Dav')?.value.trim(),pass=document.getElementById('v04Pass')?.value,user=document.getElementById('v04User')?.value||'',pwd=document.getElementById('v04Pwd')?.value||'';if(!url)return alert('Enter the complete WebDAV file URL.');const blob=await encryptSnapshot(pass);await webdav(url,user,pwd,'PUT',blob);alert('Encrypted backup uploaded. The passphrase stays in this browser only.')}
  async function getWebdav(){const url=document.getElementById('v04Dav')?.value.trim(),pass=document.getElementById('v04Pass')?.value,user=document.getElementById('v04User')?.value||'',pwd=document.getElementById('v04Pwd')?.value||'';if(!url)return alert('Enter the complete WebDAV file URL.');const r=await webdav(url,user,pwd,'GET');const x=await decryptSnapshot(await r.text(),pass);state.profile=x.profile;state.logs=x.logs;state.customSymptoms=x.customSymptoms||[];state.settings={...(x.settings||{})};await save();render();alert('Backup restored locally.')}
  async function relayPut(){const base=document.getElementById('v04Api')?.value.trim().replace(/\/$/,'');const pass=document.getElementById('v04Pass')?.value;if(!base)return alert('Enter an API base first.');localStorage.setItem(API_KEY,base);const ciphertext=await encryptSnapshot(pass);const r=await fetch(base+'/api/backup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({ciphertext})});if(!r.ok)throw Error(`Backup service returned ${r.status}.`);const x=await r.json();state.settings.relayBackupId=x.id;await save();alert(`Encrypted relay backup created. Backup ID: ${x.id}`)}
  async function relayGet(){const base=apiBase(),id=prompt('Enter the NijRitu backup ID:',state.settings?.relayBackupId||'');const pass=document.getElementById('v04Pass')?.value;if(!base||!id)return;const r=await fetch(base+'/api/backup/'+encodeURIComponent(id));if(!r.ok)throw Error(`Backup service returned ${r.status}.`);const x=await r.json();const data=await decryptSnapshot(x.ciphertext,pass);state.profile=data.profile;state.logs=data.logs;state.customSymptoms=data.customSymptoms||[];state.settings={...(data.settings||{}),relayBackupId:id};await save();render();alert('Backup restored locally.')}
  function renderFeed(items){const el=document.getElementById('communityFeed');if(!el)return;if(!items?.length){el.innerHTML='<div class="empty">No approved posts yet.</div>';return}el.innerHTML=`<div class="stat-list">${items.map(i=>`<article class="community-post"><div class="muted tiny">anonymous · ${esc(new Date(i.createdAt).toLocaleDateString())}</div><p>${esc(i.body)}</p>${i.replies?.length?`<div class="community-replies">${i.replies.map(r=>`<div class="community-reply"><div class="muted tiny">anonymous · ${esc(new Date(r.createdAt).toLocaleDateString())}</div><p>${esc(r.body)}</p></div>`).join('')}</div>`:''}<div class="button-row"><button class="button ghost small" data-action="communityReply" data-date="${esc(i.id)}">Reply${i.replyCount?` (${i.replyCount})`:''}</button><button class="button ghost small" data-action="communityReport" data-date="${esc(i.id)}">Report</button></div></article>`).join('')}</div>`}
  async function loadCommunity(){const base=apiBase(),el=document.getElementById('communityFeed');if(!el)return;if(!base){el.innerHTML='<div class="empty">Community is not connected in this build. The private tracker works without it. Add an API endpoint in Settings to enable the public layer.</div>';return}try{const r=await fetch(base+'/api/community/feed',{cache:'no-store'});if(!r.ok)throw Error();const x=await r.json();renderFeed(x.items)}catch{el.innerHTML='<div class="notice">Community is temporarily unavailable. Your private tracker is unaffected.</div>'}}
  window.community=()=>`<section class="view-head"><div><p class="eyebrow">Public layer · no profiles</p><h1>Community</h1></div></section><div class="grid"><article class="card hero"><p class="eyebrow">Anonymous by design</p><h2 class="section-title">Ask. Share. Help someone feel less alone.</h2><p class="muted">No follower graph, public profile, direct messages or targeted health advertising. Posts enter moderation before appearing publicly.</p><label class="field"><span>Share something</span><textarea id="communityBody" maxlength="5000" rows="5" placeholder="Share a question, experience or useful tip without identifying yourself."></textarea></label><button class="button primary" data-action="communitySubmit">Submit for moderation</button></article><article class="card"><div class="row"><div><p class="eyebrow">Feed</p><h2 class="section-title">Recent approved posts</h2></div><button class="button ghost small" data-action="communityRefresh">Refresh</button></div><div id="communityFeed"><div class="empty">Loading community feed…</div></div></article><article class="card"><p class="eyebrow">Boundary</p><p class="muted">Application-level anonymity does not mean the underlying network can never see technical metadata such as an IP address. Do not post names, phone numbers, addresses, medical records or other identifying information.</p></article></div>`;
  window.NijRituLoadCommunity=loadCommunity;
  window.render=function(){originalRender();if(window.view==='community'||document.querySelector('.nav-item.active')?.dataset.view==='community')setTimeout(loadCommunity,0)};
  const old=window.actions;window.actions=async function(a,k,s){try{if(a==='webdavPut')return await putWebdav();if(a==='webdavGet')return await getWebdav();if(a==='apiSave'){const v=document.getElementById('v04Api')?.value.trim().replace(/\/$/,'');if(v)localStorage.setItem(API_KEY,v);render();return}if(a==='relayPut')return await relayPut();if(a==='relayGet')return await relayGet();if(a==='communitySubmit'){const base=apiBase(),body=document.getElementById('communityBody')?.value.trim();if(!base)return alert('Add an API endpoint in Settings first.');if(!body)return alert('Write something first.');const r=await fetch(base+'/api/community/submissions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({body})});if(!r.ok)throw Error(`Community service returned ${r.status}.`);alert('Submitted for moderation.');render();return}if(a==='communityRefresh')return loadCommunity();if(a==='communityReply'){const body=prompt('Write your reply:');if(!body)return;const base=apiBase();if(!base)return alert('Add an API endpoint in Settings first.');const r=await fetch(base+'/api/community/replies',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({submissionId:k,body})});if(!r.ok)throw Error(`Community service returned ${r.status}.`);alert('Reply submitted for moderation.');return}if(a==='communityReport'){const reason=prompt('Why are you reporting this?');if(!reason)return;const base=apiBase();if(!base)return alert('Add an API endpoint in Settings first.');const r=await fetch(base+'/api/community/report',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({submissionId:k,reason})});if(!r.ok)throw Error(`Community service returned ${r.status}.`);alert('Report received.');return}return old(a,k,s)}catch(e){console.error(e);alert(e.message||'Something went wrong.')}};
})();
