/* NijRitu V0.5 Community Pro directory. Professional listings are separate from private tracker data. */
(function(){
  const KEY='nijritu.apiBase';
  const api=()=>String(localStorage.getItem(KEY)||'').replace(/\/$/,'');
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const card=()=>`<section class="view-head"><div><p class="eyebrow">Community Pro</p><h1>Find a professional</h1></div></section><div class="grid"><article class="card hero"><p class="eyebrow">Independent directory</p><h2 class="section-title">People you can choose to contact.</h2><p class="muted">A separate professional directory. Your private cycle data is never attached to a listing, search or contact request.</p><label class="field"><span>Search</span><input id="proSearch" maxlength="80" placeholder="Name, specialty or city"></label><div id="proDirectory"><div class="empty">Enter an API endpoint in Settings to load the directory.</div></div></article><article class="card"><p class="eyebrow">For professionals</p><h2 class="section-title">List your practice</h2><p class="muted">Listings are reviewed before publication. Include only professional information you are comfortable making public.</p><label class="field"><span>Name</span><input id="proName" maxlength="100"></label><label class="field"><span>Role / qualification</span><input id="proRole" maxlength="120" placeholder="e.g. Gynaecologist, counsellor"></label><label class="field"><span>Specialties</span><input id="proSpecialties" maxlength="240" placeholder="e.g. PCOS, menstrual health, adolescent care"></label><label class="field"><span>City / service area</span><input id="proLocation" maxlength="120"></label><label class="field"><span>Credential details</span><textarea id="proCredentials" maxlength="600" rows="3" placeholder="Registration or qualification details you want displayed"></textarea></label><label class="field"><span>Website / booking URL <em>optional</em></span><input id="proUrl" type="url" maxlength="500" placeholder="https://..."></label><label class="field"><span>Public contact email <em>optional</em></span><input id="proEmail" type="email" maxlength="160"></label><button class="button primary" data-action="proSubmit">Submit listing for verification</button><p class="muted tiny">Submitting creates a public-directory record, not a private health record. Do not include patient information.</p></article><article class="card"><p class="eyebrow">Verification boundary</p><p class="muted">A verified badge means NijRitu has reviewed the submitted professional credentials or evidence. It is not a guarantee of treatment quality, outcome, availability or medical advice.</p></article></div>`;
  async function loadDirectory(){const el=document.getElementById('proDirectory');if(!el)return;const base=api();if(!base){el.innerHTML='<div class="empty">Community Pro is not connected. Add an API endpoint in Settings.</div>';return}try{const r=await fetch(base+'/api/professionals',{cache:'no-store'});if(!r.ok)throw Error();const x=await r.json();window.__nijrituPro=x.items||[];renderDirectory();}catch{el.innerHTML='<div class="notice">Directory is temporarily unavailable. Your private tracker is unaffected.</div>'}}
  function renderDirectory(){const el=document.getElementById('proDirectory');if(!el)return;const q=(document.getElementById('proSearch')?.value||'').trim().toLowerCase();const items=(window.__nijrituPro||[]).filter(x=>!q||[x.name,x.role,x.specialties,x.location].join(' ').toLowerCase().includes(q));if(!items.length){el.innerHTML='<div class="empty">No verified professionals match that search.</div>';return}el.innerHTML=items.map(x=>`<article class="community-post"><div class="row"><div><h3>${esc(x.name)}</h3><div class="muted tiny">${esc(x.role)}${x.verified?' · verified':''}</div></div>${x.location?`<div class="muted tiny">${esc(x.location)}</div>`:''}</div>${x.specialties?`<p>${esc(x.specialties)}</p>`:''}${x.credentials?`<p class="muted tiny">${esc(x.credentials)}</p>`:''}<div class="button-row">${x.url?`<a class="button ghost small" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">Website / booking</a>`:''}${x.email?`<a class="button ghost small" href="mailto:${esc(x.email)}">Contact</a>`:''}</div></article>`).join('')}
  async function submit(){const base=api();if(!base)return alert('Add an API endpoint in Settings first.');const data={name:document.getElementById('proName')?.value.trim(),role:document.getElementById('proRole')?.value.trim(),specialties:document.getElementById('proSpecialties')?.value.trim(),location:document.getElementById('proLocation')?.value.trim(),credentials:document.getElementById('proCredentials')?.value.trim(),url:document.getElementById('proUrl')?.value.trim(),email:document.getElementById('proEmail')?.value.trim()};if(!data.name||!data.role||!data.credentials)return alert('Name, role / qualification and credential details are required.');if(data.url&&!/^https?:\/\//i.test(data.url))return alert('Use a complete https:// or http:// URL.');if(data.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email))return alert('Enter a valid public contact email.');const r=await fetch(base+'/api/professionals',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw Error(`Directory service returned ${r.status}.`);alert('Listing submitted for verification.');['proName','proRole','proSpecialties','proLocation','proCredentials','proUrl','proEmail'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=''});}
  window.professionals=card;
  const old=window.actions;window.actions=async function(a,k,s){try{if(a==='proSubmit')return await submit();return old(a,k,s)}catch(e){console.error(e);alert(e.message||'Something went wrong.')}};
  document.addEventListener('input',e=>{if(e.target?.id==='proSearch')renderDirectory()});
  const oldRender=window.render;window.render=function(){oldRender();if(window.view==='professionals')setTimeout(loadDirectory,0)};
})();
