/* NijRitu V0.5 Community Pro directory. Professional listings are separate from private tracker data. */
(function(){
 const KEY='nijritu.apiBase',api=()=>String(localStorage.getItem(KEY)||'').replace(/\/$/,''),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const oldCommunity=window.community;
 function directory(){return `<article class="card" id="communityPro"><div class="row"><div><p class="eyebrow">Community Pro</p><h2 class="section-title">Find a professional</h2></div><span class="tag">Separate from your tracker</span></div><p class="muted">Search verified public listings by name, specialty or city. No private cycle data is attached to this directory.</p><label class="field"><span>Search</span><input id="proSearch" maxlength="80" placeholder="Name, specialty or city"></label><div id="proDirectory"><div class="empty">Loading verified professionals…</div></div><div class="divider"></div><p class="eyebrow">For professionals</p><label class="field"><span>Name</span><input id="proName" maxlength="100"></label><label class="field"><span>Role / qualification</span><input id="proRole" maxlength="120" placeholder="e.g. Gynaecologist, counsellor"></label><label class="field"><span>Specialties</span><input id="proSpecialties" maxlength="240"></label><label class="field"><span>City / service area</span><input id="proLocation" maxlength="120"></label><label class="field"><span>Credential details</span><textarea id="proCredentials" maxlength="600" rows="3" placeholder="Registration or qualification details you want displayed"></textarea></label><label class="field"><span>Website / booking URL <em>optional</em></span><input id="proUrl" type="url" maxlength="500" placeholder="https://..."></label><label class="field"><span>Public contact email <em>optional</em></span><input id="proEmail" type="email" maxlength="160"></label><button class="button primary" data-action="proSubmit">Submit listing for verification</button><p class="muted tiny">Listings are reviewed before publication. Never include patient information.</p></article>`}
 async function load(){const el=document.getElementById('proDirectory');if(!el)return;const base=api();if(!base){el.innerHTML='<div class="empty">Add an API endpoint in Settings to enable Community Pro.</div>';return}try{const r=await fetch(base+'/api/professionals',{cache:'no-store'});if(!r.ok)throw Error();window.__nijrituPro=(await r.json()).items||[];draw()}catch{el.innerHTML='<div class="notice">Directory is temporarily unavailable. Your private tracker is unaffected.</div>'}}
 function draw(){const el=document.getElementById('proDirectory');if(!el)return;const q=(document.getElementById('proSearch')?.value||'').trim().toLowerCase(),items=(window.__nijrituPro||[]).filter(x=>!q||[x.name,x.role,x.specialties,x.location].join(' ').toLowerCase().includes(q));el.innerHTML=items.length?items.map(x=>`<article class="community-post"><div class="row"><div><h3>${esc(x.name)}</h3><div class="muted tiny">${esc(x.role)}${x.verified?' · verified':''}</div></div>${x.location?`<div class="muted tiny">${esc(x.location)}</div>`:''}</div>${x.specialties?`<p>${esc(x.specialties)}</p>`:''}${x.credentials?`<p class="muted tiny">${esc(x.credentials)}</p>`:''}<div class="button-row">${x.url?`<a class="button ghost small" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">Website / booking</a>`:''}${x.email?`<a class="button ghost small" href="mailto:${esc(x.email)}">Contact</a>`:''}</div></article>`).join(''):'<div class="empty">No verified professionals match that search.</div>'}
 const $=(id)=>document.getElementById(id)?.value.trim()||'';
 async function submit(){const base=api(),d={name:$('proName'),role:$('proRole'),specialties:$('proSpecialties'),location:$('proLocation'),credentials:$('proCredentials'),url:$('proUrl'),email:$('proEmail')};if(!base)return alert('Add an API endpoint in Settings first.');if(!d.name||!d.role||!d.credentials)return alert('Name, role / qualification and credential details are required.');if(d.url&&!/^https?:\/\//i.test(d.url))return alert('Use a complete http:// or https:// URL.');if(d.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(d.email))return alert('Enter a valid public contact email.');const r=await fetch(base+'/api/professionals',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(d)});if(!r.ok)throw Error(`Directory service returned ${r.status}.`);alert('Listing submitted for verification.');['proName','proRole','proSpecialties','proLocation','proCredentials','proUrl','proEmail'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=''})}
 window.community=()=>oldCommunity()+`<div class="grid">${directory()}</div>`;
 const old=window.actions;window.actions=async function(a,k,s){try{if(a==='proSubmit')return submit();return old(a,k,s)}catch(e){console.error(e);alert(e.message||'Something went wrong.')}};
 document.addEventListener('input',e=>{if(e.target?.id==='proSearch')draw()});
 const oldRender=window.render;window.render=function(){oldRender();if(document.querySelector('.nav-item.active')?.dataset.view==='community')setTimeout(()=>{window.NijRituLoadCommunity?.();load()},0)};
})();
