const http=require('node:http');
const crypto=require('node:crypto');
const {JsonStore}=require('./storage');
const port=Number(process.env.PORT||8787);
const store=new JsonStore(process.env.NIJRITU_STORE_FILE||'./.nijritu-data/store.json');
const adminToken=process.env.NIJRITU_ADMIN_TOKEN||'local-dev-admin';
const rate=new Map();
const json=(res,status,body)=>{const text=JSON.stringify(body);res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer'});res.end(text)};
const id=()=>crypto.randomBytes(18).toString('base64url');
const readBody=req=>new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>256*1024){reject(Error('body too large'));req.destroy()}});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch{reject(Error('invalid json'))}});req.on('error',reject)});
function limited(req,res,key,limit=20,windowMs=60000){const now=Date.now(),ip=req.socket.remoteAddress||'unknown',k=`${key}:${ip}`;const a=(rate.get(k)||[]).filter(t=>now-t<windowMs);a.push(now);rate.set(k,a);if(a.length>limit){json(res,429,{error:'rate_limited'});return true}return false}
function admin(req){return req.headers.authorization===`Bearer ${adminToken}`}
function app(req,res){const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);store.load();
 if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':process.env.NIJRITU_CORS_ORIGIN||'http://localhost:8080','access-control-allow-methods':'GET,POST,DELETE,OPTIONS','access-control-allow-headers':'content-type,authorization'});return res.end()}
 const cors=process.env.NIJRITU_CORS_ORIGIN||'http://localhost:8080';res.setHeader('access-control-allow-origin',cors);res.setHeader('vary','origin');
 if(req.method==='GET'&&u.pathname==='/api/health')return json(res,200,{ok:true,service:'nijritu-public-boundary',privateHealthData:false,storage:'durable-local-adapter'});
 if(req.method==='POST'&&u.pathname==='/api/backup'){if(limited(req,res,'backup',10))return;return readBody(req).then(b=>{if(typeof b.ciphertext!=='string'||b.ciphertext.length<20||b.ciphertext.length>2000000)return json(res,400,{error:'ciphertext_required'});const key=id();store.backups[key]={ciphertext:b.ciphertext,createdAt:new Date().toISOString(),expiresAt:typeof b.expiresAt==='string'?b.expiresAt:null};store.persist();json(res,201,{id:key})}).catch(()=>json(res,400,{error:'invalid_request'}))}
 const bm=u.pathname.match(/^\/api\/backup\/([^/]+)$/);if(bm&&req.method==='GET'){const r=store.backups[bm[1]];if(r?.expiresAt&&Date.parse(r.expiresAt)<=Date.now()){delete store.backups[bm[1]];store.persist();return json(res,404,{error:'not_found'})}return r?json(res,200,{ciphertext:r.ciphertext}):json(res,404,{error:'not_found'})}if(bm&&req.method==='DELETE'){delete store.backups[bm[1]];store.persist();return json(res,204,{})}
 if(req.method==='GET'&&u.pathname==='/api/community/feed'){const posts=store.community.filter(x=>x.status==='approved'&&x.parentId===undefined).slice(-100).reverse();const items=posts.map(({reports,...x})=>({...x,replies:store.community.filter(r=>r.parentId===x.id&&r.status==='approved').sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).map(({status,parentId,...r})=>r)}));return json(res,200,{items})}
 if(req.method==='POST'&&u.pathname==='/api/community/submissions'){if(limited(req,res,'community',5))return;return readBody(req).then(b=>{if(typeof b.body!=='string'||b.body.trim().length<1||b.body.length>5000)return json(res,400,{error:'invalid_body'});const item={id:id(),body:b.body.trim(),createdAt:new Date().toISOString(),status:'pending',replyCount:0,reports:0};store.community.push(item);store.persist();json(res,202,{id:item.id,status:'pending'})}).catch(()=>json(res,400,{error:'invalid_request'}))}
 if(req.method==='POST'&&u.pathname==='/api/community/replies'){if(limited(req,res,'replies',10))return;return readBody(req).then(b=>{if(typeof b.submissionId!=='string'||typeof b.body!=='string'||!b.body.trim()||b.body.length>3000)return json(res,400,{error:'invalid_body'});const parent=store.community.find(x=>x.id===b.submissionId&&x.status==='approved'&&x.parentId===undefined);if(!parent)return json(res,404,{error:'not_found'});const reply={id:id(),parentId:parent.id,body:b.body.trim(),createdAt:new Date().toISOString(),status:'pending'};store.community.push(reply);parent.replyCount++;store.persist();json(res,202,{id:reply.id,status:'pending'})}).catch(()=>json(res,400,{error:'invalid_request'}))}
 if(req.method==='POST'&&u.pathname==='/api/community/report'){if(limited(req,res,'reports',10))return;return readBody(req).then(b=>{if(typeof b.submissionId!=='string'||typeof b.reason!=='string'||b.reason.length<1||b.reason.length>300)return json(res,400,{error:'invalid_report'});const parent=store.community.find(x=>x.id===b.submissionId);if(!parent)return json(res,404,{error:'not_found'});parent.reports=(parent.reports||0)+1;if(parent.reports>=3&&parent.status==='approved')parent.status='review';store.persist();json(res,202,{status:'received'})}).catch(()=>json(res,400,{error:'invalid_request'}))}
 const mm=u.pathname.match(/^\/api\/moderation\/(submissions|replies)\/([^/]+)\/(approve|reject)$/);if(mm&&req.method==='POST'){if(!admin(req))return json(res,401,{error:'unauthorized'});const item=store.community.find(x=>x.id===mm[2]&&(mm[1]==='submissions'?x.parentId===undefined:x.parentId!==undefined));if(!item)return json(res,404,{error:'not_found'});item.status=mm[3]==='approve'?'approved':'rejected';store.persist();return json(res,200,{id:item.id,status:item.status})}
 if(req.method==='GET'&&u.pathname==='/api/moderation/queue'){if(!admin(req))return json(res,401,{error:'unauthorized'});return json(res,200,{items:store.community.slice(-200).reverse()})}
 json(res,404,{error:'not_found'})}
if(require.main===module)http.createServer(app).listen(port,()=>console.log(`NijRitu backend listening on ${port}`));
module.exports={app,store,rate};
