const http=require('node:http');
const crypto=require('node:crypto');
const {JsonStore}=require('./storage');
const port=Number(process.env.PORT||8787);
const store=new JsonStore(process.env.NIJRITU_STORE_FILE||'./.nijritu-data/store.json');
const isProduction=process.env.NODE_ENV==='production';
const adminToken=process.env.NIJRITU_ADMIN_TOKEN||'';
const corsOrigin=process.env.NIJRITU_CORS_ORIGIN||'http://localhost:8080';
const rate=new Map();
const json=(res,status,body)=>{const text=JSON.stringify(body);res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer','permissions-policy':'camera=(),microphone=(),geolocation=()'});res.end(text)};
const id=()=>crypto.randomBytes(18).toString('base64url');
const accessKey=()=>crypto.randomBytes(32).toString('base64url');
const keyHash=k=>crypto.createHash('sha256').update(k).digest('hex');
const readBody=req=>new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>256*1024){reject(Error('body too large'));req.destroy()}});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch{reject(Error('invalid json'))}});req.on('error',reject)});
function limited(req,res,key,limit=20,windowMs=60000){const now=Date.now(),ip=req.socket.remoteAddress||'unknown',k=`${key}:${ip}`;const a=(rate.get(k)||[]).filter(t=>now-t<windowMs);a.push(now);rate.set(k,a);if(a.length>limit){json(res,429,{error:'rate_limited'});return true}return false}
function admin(req){return Boolean(adminToken)&&req.headers.authorization===`Bearer ${adminToken}`}
function backupAuthorized(req,item){const supplied=req.headers['x-backup-key'];if(!item?.accessKeyHash||typeof supplied!=='string')return false;const a=Buffer.from(keyHash(supplied),'hex'),b=Buffer.from(item.accessKeyHash,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function backupExpiry(value){if(typeof value==='string'&&Number.isFinite(Date.parse(value)))return value;return new Date(Date.now()+90*24*60*60*1000).toISOString()}
function cleanUrl(value){if(typeof value!=='string'||!value.trim())return null;try{const u=new URL(value.trim());return ['http:','https:'].includes(u.protocol)?u.toString():null}catch{return null}}
function cleanEmail(value){if(typeof value!=='string'||!value.trim())return null;const x=value.trim();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x)?x:null}
function app(req,res){const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);store.load();
 if(req.method==='OPTIONS'){if(req.headers.origin&&req.headers.origin!==corsOrigin)return json(res,403,{error:'origin_not_allowed'});res.writeHead(204,{'access-control-allow-origin':corsOrigin,'access-control-allow-methods':'GET,POST,DELETE,OPTIONS','access-control-allow-headers':'content-type,authorization,x-backup-key','vary':'Origin'});return res.end()}
 if(req.headers.origin&&req.headers.origin!==corsOrigin)return json(res,403,{error:'origin_not_allowed'});
 res.setHeader('access-control-allow-origin',corsOrigin);res.setHeader('vary','Origin');
 if(req.method==='GET'&&u.pathname==='/api/health')return json(res,200,{ok:true,service:'nijritu-public-boundary',privateHealthData:false,storage:'durable-local-adapter',moderationConfigured:Boolean(adminToken)});
 if(req.method==='POST'&&u.pathname==='/api/backup'){if(limited(req,res,'backup',10))return;return readBody(req).then(b=>{if(typeof b.ciphertext!=='string'||b.ciphertext.length<20||b.ciphertext.length>2000000)return json(res,400,{error:'ciphertext_required'});const key=accessKey(),backupId=id();store.backups[backupId]={ciphertext:b.ciphertext,accessKeyHash:keyHash(key),createdAt:new Date().toISOString(),expiresAt:backupExpiry(b.expiresAt)};store.persist();json(res,201,{id:backupId,accessKey:key,expiresAt:store.backups[backupId].expiresAt})}).catch(()=>json(res,400,{error:'invalid_request'}))}
 const bm=u.pathname.match(/^\/api\/backup\/([^/]+)$/);if(bm&&req.method==='GET'){const r=store.backups[bm[1]];if(!r||!backupAuthorized(req,r))return json(res,404,{error:'not_found'});if(r.expiresAt&&Date.parse(r.expiresAt)<=Date.now()){delete store.backups[bm[1]];store.persist();return json(res,404,{error:'not_found'})}return json(res,200,{ciphertext:r.ciphertext,expiresAt:r.expiresAt||null})}if(bm&&req.method==='DELETE'){const r=store.backups[bm[1]];if(!r||!backupAuthorized(req,r))return json(res,404,{error:'not_found'});delete store.backups[bm[1]];store.persist();return res.writeHead(204).end()}
 if(req.method==='GET'&&u.pathname==='/api/community/feed'){const posts=store.community.filter(x=>x.status==='approved'&&x.parentId===undefined).slice(-100).reverse();const items=posts.map(({reports,...x})=>({...x,replies:store.community.filter(r=>r.parentId===x.id&&r.status==='approved').sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).map(({status,parentId,...r})=>r)}));return json(res,200,{items})}
 if(req.method==='POST'&&u.pathname==='/api/community/submissions'){if(limited(req,res,'community',5))return;return readBody(req).then(b=>{if(typeof b.body!=='string'||b.body.trim().length<1||b.body.length>5000)return json(res,400,{error:'invalid_body'});const item={id:id(),body:b.body.trim(),createdAt:new Date().toISOString(),status:'pending',replyCount:0,reports:0};store.community.push(item);store.persist();json(res,202,{id:item.id,status:'pending'})}).catch(()=>json(res,400,{error:'invalid_request'}))}
 if(req.method==='POST'&&u.pathname==='/api/community/replies'){if(limited(req,res,'replies',10))return;return readBody(req).then(b=>{if(typeof b.submissionId!=='string'||typeof b.body!=='string'||!b.body.trim()||b.body.length>3000)return json(res,400,{error:'invalid_body'});const parent=store.community.find(x=>x.id===b.submissionId&&x.status==='approved'&&x.parentId===undefined);if(!parent)return json(res,404,{error:'not_found'});const reply={id:id(),parentId:parent.id,body:b.body.trim(),createdAt:new Date().toISOString(),status:'pending'};store.community.push(reply);parent.replyCount++;store.persist();json(res,202,{id:reply.id,status:'pending'})}).catch(()=>json(res,400,{error:'invalid_request'}))}
 if(req.method==='POST'&&u.pathname==='/api/community/report'){if(limited(req,res,'reports',10))return;return readBody(req).then(b=>{if(typeof b.submissionId!=='string'||typeof b.reason!=='string'||b.reason.length<1||b.reason.length>300)return json(res,400,{error:'invalid_report'});const parent=store.community.find(x=>x.id===b.submissionId);if(!parent)return json(res,404,{error:'not_found'});parent.reports=(parent.reports||0)+1;if(parent.reports>=3&&parent.status==='approved')parent.status='review';store.persist();json(res,202,{status:'received'})}).catch(()=>json(res,400,{error:'invalid_request'}))}
 if(req.method==='GET'&&u.pathname==='/api/professionals'){const items=store.professionals.filter(x=>x.status==='approved'&&x.verified).slice(-200).reverse().map(({status,reports,submittedAt,...x})=>x);return json(res,200,{items})}
 if(req.method==='POST'&&u.pathname==='/api/professionals'){if(limited(req,res,'professionals',3))return;return readBody(req).then(b=>{const name=typeof b.name==='string'?b.name.trim():'';const role=typeof b.role==='string'?b.role.trim():'';const specialties=typeof b.specialties==='string'?b.specialties.trim():'';const location=typeof b.location==='string'?b.location.trim():'';const credentials=typeof b.credentials==='string'?b.credentials.trim():'';const url=cleanUrl(b.url);const email=cleanEmail(b.email);if(name.length<2||name.length>100||role.length<2||role.length>120||credentials.length<2||credentials.length>600||specialties.length>240||location.length>120)return json(res,400,{error:'invalid_listing'});if(b.url&&b.url.trim()&&!url)return json(res,400,{error:'invalid_url'});if(b.email&&b.email.trim()&&!email)return json(res,400,{error:'invalid_email'});const item={id:id(),name,role,specialties,location,credentials,url,email,createdAt:new Date().toISOString(),status:'pending',verified:false,reports:0};store.professionals.push(item);store.persist();json(res,202,{id:item.id,status:'pending'})}).catch(()=>json(res,400,{error:'invalid_request'}))}
 const pm=u.pathname.match(/^\/api\/moderation\/professionals\/([^/]+)\/(approve|reject|verify)$/);if(pm&&req.method==='POST'){if(!admin(req))return json(res,401,{error:'unauthorized'});const item=store.professionals.find(x=>x.id===pm[1]);if(!item)return json(res,404,{error:'not_found'});if(pm[2]==='verify'){item.verified=true;item.status='approved'}else item.status=pm[2]==='approve'?'approved':'rejected';store.persist();return json(res,200,{id:item.id,status:item.status,verified:item.verified})}
 if(req.method==='GET'&&u.pathname==='/api/moderation/professionals'){if(!admin(req))return json(res,401,{error:'unauthorized'});return json(res,200,{items:store.professionals.slice(-200).reverse()})}
 const mm=u.pathname.match(/^\/api\/moderation\/(submissions|replies)\/([^/]+)\/(approve|reject)$/);if(mm&&req.method==='POST'){if(!admin(req))return json(res,401,{error:'unauthorized'});const item=store.community.find(x=>x.id===mm[2]&&(mm[1]==='submissions'?x.parentId===undefined:x.parentId!==undefined));if(!item)return json(res,404,{error:'not_found'});item.status=mm[3]==='approve'?'approved':'rejected';store.persist();return json(res,200,{id:item.id,status:item.status})}
 if(req.method==='GET'&&u.pathname==='/api/moderation/queue'){if(!admin(req))return json(res,401,{error:'unauthorized'});return json(res,200,{items:store.community.slice(-200).reverse()})}
 json(res,404,{error:'not_found'})}
if(isProduction&&!adminToken)console.warn('NijRitu: NIJRITU_ADMIN_TOKEN is not configured; moderation endpoints are disabled.');
if(require.main===module)http.createServer(app).listen(port,()=>console.log(`NijRitu backend listening on ${port}`));
module.exports={app,store,rate};
