const fs=require('node:fs');
const assert=require('node:assert/strict');
const index=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const enhance=fs.readFileSync('ritmi-enhancements.js','utf8');
const v3=fs.readFileSync('ritmi-v3.css','utf8');
const v35=fs.readFileSync('ritmi-3-5.css','utf8');
const manifest=JSON.parse(fs.readFileSync('manifest.json','utf8'));
const demo=JSON.parse(fs.readFileSync('backend/demo-store.json','utf8'));
assert.match(index,/viewport-fit=cover/);
assert.match(index,/no-referrer/);
assert.match(index,/ritmi-3-5\.css\?v=65/);
assert.match(index,/ritmi-enhancements\.js\?v=65/);
assert.match(sw,/ritmi-3-5\.css\?v=65/);
assert.match(sw,/ritmi-enhancements\.js\?v=65/);
assert.match(sw,/ritmi-static-v3\.5\.0/);
assert.match(enhance,/quiet-nav/);
assert.match(enhance,/Primary navigation/);
assert.match(v3,/\.dock\{display:none!important\}/);
assert.match(v3,/\.quiet-popover/);
assert.match(v35,/\.quiet-links/);
assert.match(v35,/grid-template-columns:repeat\(4,1fr\)/);
assert.equal(manifest.short_name,'Ritmi');
assert.equal(manifest.name.match(/^Ritmi\b/)?.[0],'Ritmi');
assert.equal(manifest.display,'standalone');
assert.equal(manifest.orientation,'portrait-primary');
assert.equal(Array.isArray(demo.community),true);
assert.equal(Array.isArray(demo.professionals),true);
assert.equal(demo.professionals.every(x=>x.verified===true),true);
assert.equal(demo.professionals.some(x=>x.email==='demo@example.com'),true);
console.log('launch hardening checks passed');
